---
- name: verification router phase
  hosts: routers:all
  gather_facts: false
  become: yes                  
  become_method: enable
  tasks:
    - name: Execution du role Router
      ansible.builtin.include_role:
        name: router_provisioning
      when: "'routers' in group_names or (all_vlans is not defined)"

- name: switches installation
  hosts: switches:all
  gather_facts: false 
  become: yes
  become_method: enable
  tasks:
    - name: Execution du role Switch
      ansible.builtin.include_role:
        name: switch_provisioning
      when: "'switches' in group_names or (all_vlans is defined)"